Adding async private route example
mefechoel/svelte-navigator pull request #30
Opened 2021-01-30 13:17 UTC by oldtinroof

2021-01-30 13:35 UTC, oldtinroof commented
@mefechoel I have no idea why the linting is failing on one of the testApp files - I didn't open that file; I've run the lint script locally and get no issues (after my second commit on this PR where I remembered to run linting!).

2021-01-30 16:23 UTC, mefechoel commented
Thanks so much for the detailed example and description!
I'll check out the file that is causing the failure and merge this in the next couple of days.

2021-01-30 17:00 UTC, mefechoel requested changes

2021-02-01 08:25 UTC, oldtinroof commented on test/testApp/src/Main.svelte
>  				"data-has-attr": true,
How strange - I didn't open this file, I guess it got updated when I ran the lint:fix command. I wonder if I'm running a different version of Prettier or a global config got involved... Anyway, reverted now 👍

2021-02-01 08:25 UTC, oldtinroof commented on example/private-routes-async/src/App.svelte
> +		<PrivateRoute path="profile" let:location>
Sure thing 👍

2021-02-06 11:16 UTC, merged